osx_image: xcode7.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
  - os: osx
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - clang-3.7
    - graphicsmagick
    - xz-utils
    - rpm
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz | tar -xz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git-lfs-1.2.0/git-lfs pull; fi
- curl https://bootstrap.pypa.io/get-pip.py | sudo python
install:
- nvm install 6
- npm install npm -g
- npm install electron-builder@next
- npm install
- npm prune
script:
- npm run cibuild
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  artifacts:
    key: AKIAIUEBTYLXVJ74SHFQ
    secret:
      secure: K8Betbm/JiBW6T0QEYCusB8OWO7fRjmJttl3yvEJ+6MoTcW6TR5KqGZK88LINoNeVb4fq9H5rzM6ovp5WbHaXvu71yNx+wmMdHlARj+Z6NU/MA4rsHwjDEG7DklgG5UkBAun1Ha97bSql0VqKQBYQt/u2HzIFVk10Buo+wDW/Ui2Wc/s4+JYeUZKcHxkRaOXRHEjS8zO/UTjjMRecK0N8cmDra0SmyDdYkuCnKrmlexJRgKuUXBcYgaInnSl6s+n4sgll9GPBeH65GG4yYY0zbSIZhnjJ32SSDFcjRLr0ktJxWBja+HsEU7mY92ObqoPS+mGDUr4ecc1TM15KgstBekj7oSVBk81mwQ9dAd3wCA9W3T3YTt9QIrbDRiudOHCrplLME4K5uO1e8LlhosExI1bo3JLh6LknaJISTJar4skFnse2BHw65sUbsA3XOioI1veDvf5MpWIjTYmTtZUsWH+hXAt3we7A+KbKds8q7y4hFLbk2XbW+WAL6s835JsoKye/C/Yxha6+EmJHgb5FEIH/jJeT6kdYB/zF/oqXSC4Bud6wOHs09bZozonF1VmDWk2148toHQUFDR8usPodmyCNBavuYZrKz87GdH1/janZNNyuXHUAmIiWDPfBUqsCui0LkySAyi1NSKqK4QshbxFgki4rj89dpvAgaxGBvs=
    bucket: tingbot-builds
    paths:
    - dist/mac:dist/win:dist:linux
