version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run cibuildwin

artifacts:
  - path: 'dist\win\*.exe'
    name: Tide Setup

  - path: 'dist\win\*.nupkg'
    name: Tide NUPKG

  - path: 'dist\win\RELEASES'
    name: RELEASES file

  - path: 'dist\win-ia32\*.exe'
    name: Tide 32-bit Setup

  - path: 'dist\win-ia32\*.nupkg'
    name: Tide 32-bit NUPKG

  - path: 'dist\win-ia32\RELEASES'
    name: 32bit RELEASES file

deploy:
  description: ''
  provider: GitHub
  auth_token: $(GH_TOKEN)
  prerelease: true
  on:
    appveyor_repo_tag: true

test: off
